[package]
name = "wxgo"
version = "0.1.0"
description = "A Tauri App"
authors = ["jdeseva"]
license = "MIT"
repository = ""
edition = "2021"
rust-version = "1.70"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-beta.10", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0.0-beta.13", features = [] }
tauri-plugin-shell = "2.0.0-beta.3"
tauri-plugin-single-instance = "2.0.0-beta.5"
tauri-plugin-fs = "2.0.0-beta.4"
tauri-plugin-http = "2.0.0-beta.4"
